---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "modbus-tcp"
  name: modbus-tcp
  namespace: system
spec:
  ports:
    - name: tcp
      port: 5020
      targetPort: tcp
  selector:
    app.kubernetes.io/component: "modbus-tcp"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "modbus-tcp"
  name: modbus-tcp
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "modbus-tcp"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "modbus-tcp"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: simulator
          args:
            - modbus
            - tcp
          image: cnrancher/octopus-simulator:master
          imagePullPolicy: Always
          ports:
            - containerPort: 5020
              name: tcp
      terminationGracePeriodSeconds: 30
