---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "mqtt"
  name: mqtt
  namespace: system
spec:
  ports:
    - name: tcp
      port: 1883
      targetPort: tcp
  selector:
    app.kubernetes.io/component: "mqtt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "mqtt"
  name: mqtt
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "mqtt"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "mqtt"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: simulator
          args:
            - mqtt
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: cnrancher/octopus-simulator:master
          imagePullPolicy: Always
          ports:
            - containerPort: 1883
              name: tcp
      terminationGracePeriodSeconds: 30
