---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "opcua"
  name: opcua
  namespace: system
spec:
  ports:
    - name: tcp
      port: 4840
      targetPort: tcp
  selector:
    app.kubernetes.io/component: "opcua"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: "opcua"
  name: opcua
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "opcua"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "opcua"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: simulator
          image: open62541/open62541:1.0
          ports:
            - containerPort: 4840
              name: tcp
      terminationGracePeriodSeconds: 30